#!/bin/bash

#specify the theme here
ZSH_THEME="robbyrussell"

# Customise the Powerlevel9k prompts
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time load)

POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"

POWERLEVEL9K_TIME_FOREGROUND='059'
POWERLEVEL9K_TIME_BACKGROUND='004'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black' 
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='014'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='001'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='226'

POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='160'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='076'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='046'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='black'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='088'

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='033'
POWERLEVEL9K_DIR_ETC_BACKGROUND='033'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='033'
POWERLEVEL9K_DIR_HOME_BACKGROUND='033'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='red' 
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND='yellow'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='yellow'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='red'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='yellow'


POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs newline battery)
